version: '3.8'

services:
  isbd_postgres_db:
    container_name: isbd_postgres_db
    image: postgres
    restart: always
    network_mode: bridge
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: isbd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

  isbd:
    container_name: isbd
    image: "ghcr.io/sloning/isbd:latest"
    restart: always
    network_mode: bridge
    ports:
      - "443:8443"
    depends_on:
      - isbd_postgres_db
    links:
      - isbd_postgres_db
    environment:
      db_host: $db_host
      db_username: postgres
      db_password: $db_password
      SECURITY_SECRET: $SECURITY_SECRET
      key_store: $key_store
      key_store_password: $key_store_password
    volumes:
      - /home/azure/certs/isbd_keystore.p12:/home/azure/certs/isbd_keystore.p12

volumes:
  postgres_data:
    driver: local