version: '3.8'

services:
  isbd_postgres:
    container_name: isbd_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: isbd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

  isbd:
    container_name: isbd
    image: "ghcr.io/sloning/isbd:latest"
    restart: always
    depends_on:
      - isbd_postgres
    links:
      - isbd_postgres
    environment:
      db_host: jdbc:postgresql://isbd_postgres:5432/isbd
      db_username: postgres
      db_password: $db_password
      SECURITY_SECRET: $SECURITY_SECRET

volumes:
  postgres_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
